import type { Pet } from "./types";
export const mockPets: Pet[] = [
  {
    id: "1",
    name: "Кисуня",
    species: "cat",
    breed: "Шотландская вислоухая",
    color: "серый с белым",
    status: "lost",
    city: "Москва",
    district: "Хамовники",
    date: "2026-09-05",
    description:
      "Пропал возле дома на Комсомольском проспекте. Очень пугливый, на руки не даётся. На ошейнике нет адресника.",
    photoUrl: "/images/kisunya.JPG",
    contactName: "Венера Смирнова",
    contactPhone: "+7 900 111-22-33",
  },
  {
    id: "2",
    name: "Чупек",
    species: "dog",
    breed: "Немецкий шпиц",
    color: "белый",
    status: "lost",
    city: "Москва",
    district: "Сокольники",
    date: "2026-09-08",
    description:
      "Убежал в парке Сокольники во время грозы, испугался салюта. Отзывается на кличку, в наморднике.",
    photoUrl: "/images/bobik.jpg",
    contactName: "Юля Петрова",
    contactPhone: "+7 900 222-33-44",
  },
  {
    id: "3",
    name: "Буся",
    species: "cat",
    breed: "Британская короткошёрстная",
    color: "серый",
    status: "found",
    city: "Санкт-Петербург",
    district: "Петроградский район",
    date: "2026-09-02",
    description:
      "Нашли у подъезда, упитанная, ухоженная — явно домашняя. Сидит у меня, ищем хозяев.",
    photoUrl: "/images/buchek.jpg",
    contactName: "Аня Кузнецова",
    contactPhone: "+7 900 333-44-55",
  },
  {
    id: "4",
    name: "Кличка неизвестна",
    species: "dog",
    breed: "Метис, похож на джек рассел терьера",
    color: "триколор",
    status: "found",
    city: "Новосибирск",
    date: "2026-09-09",
    description:
      "Бегал один по Красному проспекту, поймали и передержали дома. Молодой, вежливый, знает команду «сидеть».",
    photoUrl: "/images/maksek.JPG",
    contactName: "Дмитрий Волков",
    contactPhone: "+7 900 444-55-66",
  },
  {
    id: "5",
    name: "Симба",
    species: "dog",
    breed: "Джек рассел",
    color: "рыжый, белый ",
    status: "lost",
    city: "Казань",
    district: "Вахитовский район",
    date: "2026-09-01",
    description: "Крупный кот, пропал с балкона. Очень общительный, может подойти к людям сам.",
    photoUrl: "/images/maksek1.JPG",
    contactName: "Марат Гареев",
    contactPhone: "+7 900 555-66-77",
  },
  {
    id: "6",
    name: "Люси",
    species: "dog",
    breed: "Джек-рассел-терьер",
    color: "бело-рыжий",
    status: "lost",
    city: "Екатеринбург",
    date: "2026-09-07",
    description: "Потерялась на прогулке в парке Маяковского, была без поводка. Очень активная и шумная.",
    photoUrl: "/images/maksek2.JPG",
    contactName: "Елена Жукова",
    contactPhone: "+7 900 666-77-88",
  },
  {
    id: "7",
    name: "Кличка неизвестна",
    species: "cat",
    breed: "Дворовая",
    color: "чёрный",
    status: "found",
    city: "Москва",
    district: "Пресненский район",
    date: "2026-09-06",
    description: "Молодая кошка, пришла на балкон и осталась. Стерилизована, судя по метке на ухе.",
    photoUrl: "/images/son_kisunya.JPG",
    contactName: "Светлана Орлова",
    contactPhone: "+7 900 777-88-99",
  },
  {
    id: "8",
    name: "Граф",
    species: "dog",
    breed: "Чихуахуа",
    color: "коричневый",
    status: "lost",
    city: "Санкт-Петербург",
    district: "Василеостровский район",
    date: "2026-09-04",
    description: "Убежал со двора через приоткрытую калитку. Немного прихрамывает на переднюю лапу.",
    photoUrl: "/images/kisunya_diva.JPG",
    contactName: "Николай Соколов",
    contactPhone: "+7 900 888-99-00",
  },
  {
    id: "9",
    name: "Ася",
    species: "other",
    breed: "неопозанный объект",
    color: "белый с серым",
    status: "lost",
    city: "Москва",
    district: "Люблино",
    date: "2026-09-10",
    description: "Выбралась из вольера на даче. Ручная, но пугается громких звуков.",
    photoUrl: "/images/puki.JPG",
    contactName: "Мария Титова",
    contactPhone: "+7 900 999-00-11",
  },
];

export const currentUserPets: Pet[] = [mockPets[0]];

export function getMockSearchResults(): Pet[] {
  const order = ["2", "6", "8", "4"];
  const scores = [92, 78, 61, 54];
  return order
    .map((id) => mockPets.find((pet) => pet.id === id))
    .filter((pet): pet is Pet => Boolean(pet))
    .map((pet, index) => ({ ...pet, matchScore: scores[index] }));
}
